/**
 * JSON Schema for the public `Profile` artifact (D8), hand-kept in lockstep
 * with the `Profile` type in profile.ts — that type is the source of truth;
 * this is its schema projection. `profile.test.ts` asserts a real assembled
 * profile validates structurally against it, so the two cannot drift silently.
 */
export const PROFILE_JSON_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "claude-profiler Profile",
  type: "object",
  required: [
    "schemaVersion",
    "generatedAt",
    "generator",
    "session",
    "timeline",
    "modelBreakdown",
    "tools",
    "subagents",
    "tokens",
    "cost",
    "context",
    "prompts",
    "hooks",
    "phases",
    "diagnostics",
  ],
  properties: {
    schemaVersion: { const: "0.2" },
    generatedAt: { type: "string", format: "date-time" },
    generator: {
      type: "object",
      required: ["name", "version"],
      properties: {
        name: { type: "string" },
        version: { type: "string" },
      },
    },
    session: { $ref: "#/$defs/sessionMeta" },
    timeline: { $ref: "#/$defs/timeSplit" },
    modelBreakdown: { $ref: "#/$defs/modelBreakdown" },
    tools: { type: "array", items: { $ref: "#/$defs/toolStat" } },
    subagents: { type: "array", items: { $ref: "#/$defs/subagentStat" } },
    tokens: { $ref: "#/$defs/tokenStats" },
    cost: { oneOf: [{ $ref: "#/$defs/costStats" }, { type: "null" }] },
    context: { $ref: "#/$defs/contextSeries" },
    prompts: { type: "array", items: { $ref: "#/$defs/promptPoint" } },
    hooks: { oneOf: [{ $ref: "#/$defs/hookInsights" }, { type: "null" }] },
    phases: { oneOf: [{ $ref: "#/$defs/phaseSplit" }, { type: "null" }] },
    diagnostics: {
      type: "object",
      required: ["skippedLines", "unknownRecordTypes", "unmatchedToolUses", "versionsSeen"],
      properties: {
        skippedLines: { type: "integer", minimum: 0 },
        unknownRecordTypes: { type: "object", additionalProperties: { type: "integer", minimum: 0 } },
        unmatchedToolUses: { type: "integer", minimum: 0 },
        versionsSeen: { type: "array", items: { type: "string" } },
      },
    },
  },
  $defs: {
    sessionMeta: {
      type: "object",
      required: [
        "sessionId",
        "transcriptPath",
        "spanMs",
        "ccVersions",
        "models",
        "turnCount",
        "messageCount",
        "isSidechain",
      ],
      properties: {
        sessionId: { type: "string" },
        transcriptPath: { type: "string" },
        projectPath: { type: ["string", "null"] },
        gitBranch: { type: ["string", "null"] },
        title: { type: ["string", "null"] },
        startedAt: { type: ["string", "null"], format: "date-time" },
        endedAt: { type: ["string", "null"], format: "date-time" },
        spanMs: { type: "number", minimum: 0 },
        ccVersions: { type: "array", items: { type: "string" } },
        models: { type: "array", items: { type: "string" } },
        turnCount: { type: "integer", minimum: 0 },
        messageCount: { type: "integer", minimum: 0 },
        isSidechain: { type: "boolean" },
      },
    },
    timeSplit: {
      type: "object",
      required: [
        "modelMs",
        "toolsMs",
        "userMs",
        "unaccountedMs",
        "spanMs",
        "toolsIncludeApprovals",
        "precision",
        "userGaps",
      ],
      properties: {
        modelMs: { type: "number", minimum: 0 },
        toolsMs: { type: "number", minimum: 0 },
        userMs: { type: "number", minimum: 0 },
        unaccountedMs: { type: "number", minimum: 0 },
        spanMs: { type: "number", minimum: 0 },
        toolsIncludeApprovals: { const: true },
        precision: { enum: ["derived", "exact"] },
        userGaps: {
          type: "array",
          items: {
            type: "object",
            required: ["preview", "gapMs"],
            properties: {
              preview: { type: "string" },
              gapMs: { type: "number", minimum: 0 },
            },
          },
        },
      },
    },
    toolCall: {
      type: "object",
      required: ["id", "name", "turnIndex", "startedAt", "durationMs", "inputPreview"],
      properties: {
        id: { type: "string" },
        name: { type: "string" },
        turnIndex: { type: "integer", minimum: 0 },
        startedAt: { type: ["string", "null"] },
        durationMs: { type: ["number", "null"] },
        inputPreview: { type: "string" },
        subagentRef: { type: "string" },
      },
    },
    toolStat: {
      type: "object",
      required: [
        "name",
        "kind",
        "calls",
        "totalMs",
        "typicalMs",
        "medianMs",
        "p90Ms",
        "maxMs",
        "unfinishedCount",
        "pctOfSession",
        "callRefs",
        "exactMs",
        "approvalMs",
      ],
      properties: {
        name: { type: "string" },
        kind: { enum: ["builtin", "mcp", "task"] },
        mcpServer: { type: ["string", "null"] },
        calls: { type: "integer", minimum: 0 },
        totalMs: { type: "number", minimum: 0 },
        typicalMs: { type: "number", minimum: 0 },
        medianMs: { type: "number", minimum: 0 },
        p90Ms: { type: "number", minimum: 0 },
        maxMs: { type: "number", minimum: 0 },
        unfinishedCount: { type: "integer", minimum: 0 },
        pctOfSession: { type: "number", minimum: 0 },
        callRefs: { type: "array", items: { $ref: "#/$defs/toolCall" } },
        exactMs: { type: ["number", "null"] },
        approvalMs: { type: ["number", "null"] },
        approvalPrecision: { enum: ["split", "unsplit", null] },
        overheadMs: { type: ["number", "null"] },
        promptedCalls: { type: "integer", minimum: 0 },
        failedCalls: { type: "integer", minimum: 0 },
        interruptedCalls: { type: "integer", minimum: 0 },
        deniedCalls: { type: "integer", minimum: 0 },
        responseBytes: { type: ["number", "null"] },
        bashGroups: { type: "array", items: { $ref: "#/$defs/bashGroupStat" } },
      },
    },
    bashGroupStat: {
      type: "object",
      required: ["group", "calls", "totalMs", "medianMs", "maxMs", "unfinishedCount", "pctOfBash", "callIds"],
      properties: {
        group: { type: "string" },
        calls: { type: "integer", minimum: 0 },
        totalMs: { type: "number", minimum: 0 },
        medianMs: { type: "number", minimum: 0 },
        maxMs: { type: "number", minimum: 0 },
        unfinishedCount: { type: "integer", minimum: 0 },
        pctOfBash: { type: "number", minimum: 0 },
        callIds: { type: "array", items: { type: "string" } },
      },
    },
    subagentStat: {
      type: "object",
      required: [
        "agentId",
        "transcriptPath",
        "parentToolCallId",
        "spanMs",
        "timeline",
        "modelBreakdown",
        "tools",
        "tokens",
      ],
      properties: {
        agentId: { type: "string" },
        transcriptPath: { type: "string" },
        parentToolCallId: { type: "string" },
        spanMs: { type: "number", minimum: 0 },
        timeline: { $ref: "#/$defs/timeSplit" },
        modelBreakdown: { $ref: "#/$defs/modelBreakdown" },
        tools: { type: "array", items: { $ref: "#/$defs/toolStat" } },
        tokens: { $ref: "#/$defs/tokenStats" },
      },
    },
    blockKind: { enum: ["thinking", "text", "tool_use", "other"] },
    modelPhase: {
      type: "object",
      required: ["kind", "position", "ms", "pctOfModel", "slices"],
      properties: {
        kind: { $ref: "#/$defs/blockKind" },
        position: { enum: ["first", "continuation"] },
        ms: { type: "number", minimum: 0 },
        pctOfModel: { type: "number", minimum: 0 },
        slices: { type: "integer", minimum: 0 },
      },
    },
    modelRequest: {
      type: "object",
      required: [
        "key",
        "requestId",
        "index",
        "turnIndex",
        "at",
        "stopReason",
        "totalMs",
        "firstBlockMs",
        "continuationMs",
        "outputTokens",
        "thinkingTokens",
        "contextTokens",
        "tokensPerSec",
        "blocks",
        "cause",
        "suspect",
        "preview",
      ],
      properties: {
        key: { type: "string" },
        requestId: { type: ["string", "null"] },
        index: { type: "integer", minimum: 0 },
        turnIndex: { type: "integer", minimum: 0 },
        at: { type: ["string", "null"] },
        model: { type: ["string", "null"] },
        effort: { type: ["string", "null"] },
        stopReason: { type: ["string", "null"] },
        totalMs: { type: "number", minimum: 0 },
        firstBlockMs: { type: "number", minimum: 0 },
        continuationMs: { type: "number", minimum: 0 },
        outputTokens: { type: "number", minimum: 0 },
        thinkingTokens: { type: "number", minimum: 0 },
        contextTokens: { type: "number", minimum: 0 },
        tokensPerSec: { type: ["number", "null"] },
        blocks: { type: "array", items: { $ref: "#/$defs/blockKind" } },
        cause: {
          type: "object",
          required: ["kind", "name"],
          properties: {
            kind: { enum: ["prompt", "tool", "other"] },
            name: { type: ["string", "null"] },
          },
        },
        suspect: { oneOf: [{ enum: ["api_error", "stalled"] }, { type: "null" }] },
        preview: { type: "string" },
      },
    },
    modelRollup: {
      type: "object",
      required: ["key", "ms", "requests", "pctOfModel"],
      properties: {
        key: { type: "string" },
        ms: { type: "number", minimum: 0 },
        requests: { type: "integer", minimum: 0 },
        pctOfModel: { type: "number", minimum: 0 },
      },
    },
    modelBreakdown: {
      type: "object",
      required: [
        "totalMs",
        "phases",
        "requests",
        "suspect",
        "suspectMs",
        "stallThresholdTokensPerSec",
        "contextLatency",
        "byCause",
        "byModel",
        "byEffort",
        "coverage",
        "precision",
      ],
      properties: {
        totalMs: { type: "number", minimum: 0 },
        phases: { type: "array", items: { $ref: "#/$defs/modelPhase" } },
        requests: { type: "array", items: { $ref: "#/$defs/modelRequest" } },
        suspect: {
          type: "array",
          items: {
            type: "object",
            required: ["reason", "ms", "requests", "pctOfModel", "kinds"],
            properties: {
              reason: { enum: ["api_error", "stalled"] },
              ms: { type: "number", minimum: 0 },
              requests: { type: "integer", minimum: 0 },
              pctOfModel: { type: "number", minimum: 0 },
              kinds: { type: "array", items: { type: "string" } },
            },
          },
        },
        suspectMs: { type: "number", minimum: 0 },
        stallThresholdTokensPerSec: { type: "number", minimum: 0 },
        contextLatency: {
          oneOf: [
            {
              type: "object",
              required: ["correlation", "requests"],
              properties: {
                correlation: { type: "number", minimum: -1, maximum: 1 },
                requests: { type: "integer", minimum: 0 },
              },
            },
            { type: "null" },
          ],
        },
        byCause: { type: "array", items: { $ref: "#/$defs/modelRollup" } },
        byModel: { type: "array", items: { $ref: "#/$defs/modelRollup" } },
        byEffort: { type: "array", items: { $ref: "#/$defs/modelRollup" } },
        coverage: {
          type: "object",
          required: ["requestsWithBlockSplit", "totalRequests"],
          properties: {
            requestsWithBlockSplit: { type: "integer", minimum: 0 },
            totalRequests: { type: "integer", minimum: 0 },
          },
        },
        precision: { const: "measured" },
      },
    },
    tokenBucket: {
      type: "object",
      required: ["input", "output", "thinking", "cacheRead", "cacheCreate1h", "cacheCreate5m"],
      properties: {
        input: { type: "number", minimum: 0 },
        output: { type: "number", minimum: 0 },
        thinking: { type: "number", minimum: 0 },
        cacheRead: { type: "number", minimum: 0 },
        cacheCreate1h: { type: "number", minimum: 0 },
        cacheCreate5m: { type: "number", minimum: 0 },
      },
    },
    tokenStats: {
      type: "object",
      required: ["byModel", "totals"],
      properties: {
        byModel: { type: "object", additionalProperties: { $ref: "#/$defs/tokenBucket" } },
        totals: { $ref: "#/$defs/tokenBucket" },
      },
    },
    costStats: {
      type: "object",
      required: [
        "source",
        "totalCostUSD",
        "byModel",
        "totalApiDurationMs",
        "totalToolDurationMs",
        "totalDurationMs",
        "linesAdded",
        "linesRemoved",
      ],
      properties: {
        source: { const: "cost-state" },
        totalCostUSD: { type: "number", minimum: 0 },
        byModel: { type: "object", additionalProperties: { type: "number" } },
        totalApiDurationMs: { type: "number", minimum: 0 },
        totalToolDurationMs: { type: "number", minimum: 0 },
        totalDurationMs: { type: "number", minimum: 0 },
        linesAdded: { type: "number", minimum: 0 },
        linesRemoved: { type: "number", minimum: 0 },
      },
    },
    promptPoint: {
      type: "object",
      required: ["turnIndex", "at", "preview"],
      properties: {
        turnIndex: { type: "integer", minimum: 0 },
        at: { type: ["string", "null"] },
        preview: { type: "string" },
      },
    },
    phaseSplit: {
      type: "object",
      required: [
        "modelMs",
        "toolsMs",
        "userMs",
        "idleMs",
        "unaccountedMs",
        "spanMs",
        "phases",
        "reclaimedFromUserMs",
        "reclaimedFromUnaccountedMs",
      ],
      properties: {
        modelMs: { type: "number", minimum: 0 },
        toolsMs: { type: "number", minimum: 0 },
        userMs: { type: "number", minimum: 0 },
        idleMs: { type: "number", minimum: 0 },
        unaccountedMs: { type: "number", minimum: 0 },
        spanMs: { type: "number", minimum: 0 },
        reclaimedFromUserMs: { type: "number", minimum: 0 },
        reclaimedFromUnaccountedMs: { type: "number", minimum: 0 },
        phases: {
          type: "array",
          items: {
            type: "object",
            required: ["resumedAt", "source", "idleMs", "fromUserMs"],
            properties: {
              resumedAt: { type: "string" },
              source: { type: "string" },
              idleMs: { type: "number", minimum: 0 },
              fromUserMs: { type: "number", minimum: 0 },
              cacheWriteUsd: { type: ["number", "null"] },
              cacheLikelyExpired: { type: ["boolean", "null"] },
            },
          },
        },
      },
    },
    hookInsights: {
      type: "object",
      required: [
        "sidecarVersion",
        "callsWithTiming",
        "approval",
        "reliability",
        "parallelism",
        "contextPollution",
        "lifecycle",
        "cacheWaste",
        "compaction",
        "turns",
        "commands",
        "instructions",
        "streaming",
        "subagents",
      ],
      properties: {
        sidecarVersion: { type: "integer", minimum: 1 },
        callsWithTiming: { type: "integer", minimum: 0 },
        approval: {
          type: "object",
          required: [
            "precision",
            "decisionMs",
            "overheadMs",
            "totalWaitMs",
            "promptedCalls",
            "autoApprovedCalls",
            "deniedCalls",
            "slowestDecisionMs",
            "medianDecisionMs",
          ],
          properties: {
            precision: { enum: ["split", "unsplit"] },
            decisionMs: { type: ["number", "null"] },
            overheadMs: { type: ["number", "null"] },
            totalWaitMs: { type: "number", minimum: 0 },
            promptedCalls: { type: "integer", minimum: 0 },
            autoApprovedCalls: { type: "integer", minimum: 0 },
            deniedCalls: { type: "integer", minimum: 0 },
            slowestDecisionMs: { type: ["number", "null"] },
            medianDecisionMs: { type: ["number", "null"] },
          },
        },
        reliability: {
          type: "object",
          required: ["failedCalls", "interruptedCalls", "deniedCalls", "wastedMs", "byTool"],
          properties: {
            failedCalls: { type: "integer", minimum: 0 },
            interruptedCalls: { type: "integer", minimum: 0 },
            deniedCalls: { type: "integer", minimum: 0 },
            wastedMs: { type: "number", minimum: 0 },
            byTool: {
              type: "array",
              items: {
                type: "object",
                required: ["name", "failedCalls", "interruptedCalls", "wastedMs"],
                properties: {
                  name: { type: "string" },
                  failedCalls: { type: "integer", minimum: 0 },
                  interruptedCalls: { type: "integer", minimum: 0 },
                  wastedMs: { type: "number", minimum: 0 },
                  errorPreview: { type: ["string", "null"] },
                },
              },
            },
          },
        },
        parallelism: {
          oneOf: [
            {
              type: "object",
              required: ["batches", "multiCallBatches", "largestBatch", "serialMs", "wallMs", "savedMs"],
              properties: {
                batches: { type: "integer", minimum: 0 },
                multiCallBatches: { type: "integer", minimum: 0 },
                largestBatch: { type: "integer", minimum: 0 },
                serialMs: { type: ["number", "null"] },
                wallMs: { type: ["number", "null"] },
                savedMs: { type: ["number", "null"] },
              },
            },
            { type: "null" },
          ],
        },
        contextPollution: {
          oneOf: [
            {
              type: "object",
              required: ["totalBytes", "maxBytes", "byTool"],
              properties: {
                totalBytes: { type: "number", minimum: 0 },
                maxBytes: { type: "number", minimum: 0 },
                byTool: {
                  type: "array",
                  items: {
                    type: "object",
                    required: ["name", "calls", "totalBytes", "maxBytes", "medianBytes"],
                    properties: {
                      name: { type: "string" },
                      calls: { type: "integer", minimum: 0 },
                      totalBytes: { type: "number", minimum: 0 },
                      maxBytes: { type: "number", minimum: 0 },
                      medianBytes: { type: "number", minimum: 0 },
                    },
                  },
                },
              },
            },
            { type: "null" },
          ],
        },
        lifecycle: {
          type: "object",
          required: [
            "starts",
            "idleMs",
            "turnsWaitingOnBackground",
            "turnEnds",
            "humanPrompts",
            "machinePrompts",
            "promptSources",
          ],
          properties: {
            starts: {
              type: "array",
              items: {
                type: "object",
                required: ["at", "source", "idleMs"],
                properties: {
                  at: { type: "string" },
                  source: { type: "string" },
                  model: { type: ["string", "null"] },
                  idleMs: { type: ["number", "null"] },
                  contextTokens: { type: ["number", "null"] },
                  cacheLikelyExpired: { type: ["boolean", "null"] },
                  cacheWriteUsd: { type: ["number", "null"] },
                },
              },
            },
            endReason: { type: ["string", "null"] },
            idleMs: { type: "number", minimum: 0 },
            turnsWaitingOnBackground: { type: "integer", minimum: 0 },
            turnEnds: { type: "integer", minimum: 0 },
            humanPrompts: { type: "integer", minimum: 0 },
            machinePrompts: { type: "integer", minimum: 0 },
            promptSources: { type: "object", additionalProperties: { type: "integer", minimum: 0 } },
          },
        },
        cacheWaste: {
          oneOf: [
            {
              type: "object",
              required: [
                "resumeUsd",
                "modelSwitchUsd",
                "totalUsd",
                "resumes",
                "modelSwitches",
                "switchesForfeitingWarmCache",
                "pricing",
              ],
              properties: {
                resumeUsd: { type: ["number", "null"] },
                modelSwitchUsd: { type: ["number", "null"] },
                totalUsd: { type: ["number", "null"] },
                resumes: { type: "integer", minimum: 0 },
                modelSwitches: { type: "integer", minimum: 0 },
                switchesForfeitingWarmCache: { type: "integer", minimum: 0 },
                pricing: { type: "array", items: { type: "string" } },
              },
            },
            { type: "null" },
          ],
        },
        compaction: {
          oneOf: [
            {
              type: "object",
              required: ["count", "autoCount", "manualCount", "totalMs", "summaryBytes"],
              properties: {
                count: { type: "integer", minimum: 0 },
                autoCount: { type: "integer", minimum: 0 },
                manualCount: { type: "integer", minimum: 0 },
                totalMs: { type: ["number", "null"] },
                summaryBytes: { type: ["number", "null"] },
              },
            },
            { type: "null" },
          ],
        },
        turns: {
          type: "array",
          items: {
            type: "object",
            required: ["promptId", "toolCalls", "toolExecMs", "decisionMs", "failedCalls", "responseBytes"],
            properties: {
              promptId: { type: "string" },
              source: { type: ["string", "null"] },
              commandName: { type: ["string", "null"] },
              toolCalls: { type: "integer", minimum: 0 },
              toolExecMs: { type: "number", minimum: 0 },
              decisionMs: { type: ["number", "null"] },
              failedCalls: { type: "integer", minimum: 0 },
              responseBytes: { type: ["number", "null"] },
              effort: { type: ["string", "null"] },
            },
          },
        },
        commands: {
          type: "array",
          items: {
            type: "object",
            required: ["commandName", "runs", "toolCalls", "toolExecMs"],
            properties: {
              commandName: { type: "string" },
              runs: { type: "integer", minimum: 0 },
              toolCalls: { type: "integer", minimum: 0 },
              toolExecMs: { type: "number", minimum: 0 },
            },
          },
        },
        instructions: {
          oneOf: [
            {
              type: "object",
              required: ["files", "totalLoads"],
              properties: {
                totalLoads: { type: "integer", minimum: 0 },
                files: {
                  type: "array",
                  items: {
                    type: "object",
                    required: ["filePath", "loads"],
                    properties: {
                      filePath: { type: "string" },
                      memoryType: { type: ["string", "null"] },
                      loadReason: { type: ["string", "null"] },
                      loads: { type: "integer", minimum: 0 },
                    },
                  },
                },
              },
            },
            { type: "null" },
          ],
        },
        streaming: {
          oneOf: [
            {
              type: "object",
              required: [
                "messages",
                "medianStreamMs",
                "p90StreamMs",
                "totalDeltaBytes",
                "incompleteMessages",
              ],
              properties: {
                messages: { type: "integer", minimum: 0 },
                medianStreamMs: { type: "number", minimum: 0 },
                p90StreamMs: { type: "number", minimum: 0 },
                totalDeltaBytes: { type: "number", minimum: 0 },
                incompleteMessages: { type: "integer", minimum: 0 },
              },
            },
            { type: "null" },
          ],
        },
        subagents: {
          type: "array",
          items: {
            type: "object",
            required: ["subagentId", "spanMs", "toolCalls", "toolExecMs"],
            properties: {
              subagentId: { type: "string" },
              subagentType: { type: ["string", "null"] },
              transcriptPath: { type: ["string", "null"] },
              spanMs: { type: ["number", "null"] },
              toolCalls: { type: "integer", minimum: 0 },
              toolExecMs: { type: "number", minimum: 0 },
            },
          },
        },
      },
    },
    contextSeries: {
      type: "object",
      required: ["turns"],
      properties: {
        turns: {
          type: "array",
          items: {
            type: "object",
            required: ["turnIndex", "at", "cacheReadTokens", "cacheCreateTokens", "outputTokens", "thinkingTokens"],
            properties: {
              turnIndex: { type: "integer", minimum: 0 },
              at: { type: ["string", "null"] },
              cacheReadTokens: { type: "number", minimum: 0 },
              cacheCreateTokens: { type: "number", minimum: 0 },
              outputTokens: { type: "number", minimum: 0 },
              thinkingTokens: { type: "number", minimum: 0 },
            },
          },
        },
      },
    },
  },
} as const;
