/**
 * JSON Schema for the public `Profile` artifact (D8), hand-kept in lockstep
 * with the `Profile` type in profile.ts — that type is the source of truth;
 * this is its schema projection. `profile.test.ts` asserts a real assembled
 * profile validates structurally against it, so the two cannot drift silently.
 */
export const PROFILE_JSON_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "claude-profiler Profile",
  type: "object",
  required: [
    "schemaVersion",
    "generatedAt",
    "generator",
    "session",
    "timeline",
    "modelBreakdown",
    "tools",
    "subagents",
    "tokens",
    "cost",
    "context",
    "prompts",
    "diagnostics",
  ],
  properties: {
    schemaVersion: { const: "0.1" },
    generatedAt: { type: "string", format: "date-time" },
    generator: {
      type: "object",
      required: ["name", "version"],
      properties: {
        name: { type: "string" },
        version: { type: "string" },
      },
    },
    session: { $ref: "#/$defs/sessionMeta" },
    timeline: { $ref: "#/$defs/timeSplit" },
    modelBreakdown: { $ref: "#/$defs/modelBreakdown" },
    tools: { type: "array", items: { $ref: "#/$defs/toolStat" } },
    subagents: { type: "array", items: { $ref: "#/$defs/subagentStat" } },
    tokens: { $ref: "#/$defs/tokenStats" },
    cost: { oneOf: [{ $ref: "#/$defs/costStats" }, { type: "null" }] },
    context: { $ref: "#/$defs/contextSeries" },
    prompts: { type: "array", items: { $ref: "#/$defs/promptPoint" } },
    diagnostics: {
      type: "object",
      required: ["skippedLines", "unknownRecordTypes", "unmatchedToolUses", "versionsSeen"],
      properties: {
        skippedLines: { type: "integer", minimum: 0 },
        unknownRecordTypes: { type: "object", additionalProperties: { type: "integer", minimum: 0 } },
        unmatchedToolUses: { type: "integer", minimum: 0 },
        versionsSeen: { type: "array", items: { type: "string" } },
      },
    },
  },
  $defs: {
    sessionMeta: {
      type: "object",
      required: [
        "sessionId",
        "transcriptPath",
        "spanMs",
        "ccVersions",
        "models",
        "turnCount",
        "messageCount",
        "isSidechain",
      ],
      properties: {
        sessionId: { type: "string" },
        transcriptPath: { type: "string" },
        projectPath: { type: ["string", "null"] },
        gitBranch: { type: ["string", "null"] },
        title: { type: ["string", "null"] },
        startedAt: { type: ["string", "null"], format: "date-time" },
        endedAt: { type: ["string", "null"], format: "date-time" },
        spanMs: { type: "number", minimum: 0 },
        ccVersions: { type: "array", items: { type: "string" } },
        models: { type: "array", items: { type: "string" } },
        turnCount: { type: "integer", minimum: 0 },
        messageCount: { type: "integer", minimum: 0 },
        isSidechain: { type: "boolean" },
      },
    },
    timeSplit: {
      type: "object",
      required: [
        "modelMs",
        "toolsMs",
        "userMs",
        "unaccountedMs",
        "spanMs",
        "toolsIncludeApprovals",
        "precision",
        "userGaps",
      ],
      properties: {
        modelMs: { type: "number", minimum: 0 },
        toolsMs: { type: "number", minimum: 0 },
        userMs: { type: "number", minimum: 0 },
        unaccountedMs: { type: "number", minimum: 0 },
        spanMs: { type: "number", minimum: 0 },
        toolsIncludeApprovals: { const: true },
        precision: { enum: ["derived", "exact"] },
        userGaps: {
          type: "array",
          items: {
            type: "object",
            required: ["preview", "gapMs"],
            properties: {
              preview: { type: "string" },
              gapMs: { type: "number", minimum: 0 },
            },
          },
        },
      },
    },
    toolCall: {
      type: "object",
      required: ["id", "name", "turnIndex", "startedAt", "durationMs", "inputPreview"],
      properties: {
        id: { type: "string" },
        name: { type: "string" },
        turnIndex: { type: "integer", minimum: 0 },
        startedAt: { type: ["string", "null"] },
        durationMs: { type: ["number", "null"] },
        inputPreview: { type: "string" },
        subagentRef: { type: "string" },
      },
    },
    toolStat: {
      type: "object",
      required: [
        "name",
        "kind",
        "calls",
        "totalMs",
        "typicalMs",
        "medianMs",
        "p90Ms",
        "maxMs",
        "unfinishedCount",
        "pctOfSession",
        "callRefs",
        "exactMs",
        "approvalMs",
      ],
      properties: {
        name: { type: "string" },
        kind: { enum: ["builtin", "mcp", "task"] },
        mcpServer: { type: ["string", "null"] },
        calls: { type: "integer", minimum: 0 },
        totalMs: { type: "number", minimum: 0 },
        typicalMs: { type: "number", minimum: 0 },
        medianMs: { type: "number", minimum: 0 },
        p90Ms: { type: "number", minimum: 0 },
        maxMs: { type: "number", minimum: 0 },
        unfinishedCount: { type: "integer", minimum: 0 },
        pctOfSession: { type: "number", minimum: 0 },
        callRefs: { type: "array", items: { $ref: "#/$defs/toolCall" } },
        exactMs: { type: ["number", "null"] },
        approvalMs: { type: ["number", "null"] },
        bashGroups: { type: "array", items: { $ref: "#/$defs/bashGroupStat" } },
      },
    },
    bashGroupStat: {
      type: "object",
      required: ["group", "calls", "totalMs", "medianMs", "maxMs", "unfinishedCount", "pctOfBash", "callIds"],
      properties: {
        group: { type: "string" },
        calls: { type: "integer", minimum: 0 },
        totalMs: { type: "number", minimum: 0 },
        medianMs: { type: "number", minimum: 0 },
        maxMs: { type: "number", minimum: 0 },
        unfinishedCount: { type: "integer", minimum: 0 },
        pctOfBash: { type: "number", minimum: 0 },
        callIds: { type: "array", items: { type: "string" } },
      },
    },
    subagentStat: {
      type: "object",
      required: [
        "agentId",
        "transcriptPath",
        "parentToolCallId",
        "spanMs",
        "timeline",
        "modelBreakdown",
        "tools",
        "tokens",
      ],
      properties: {
        agentId: { type: "string" },
        transcriptPath: { type: "string" },
        parentToolCallId: { type: "string" },
        spanMs: { type: "number", minimum: 0 },
        timeline: { $ref: "#/$defs/timeSplit" },
        modelBreakdown: { $ref: "#/$defs/modelBreakdown" },
        tools: { type: "array", items: { $ref: "#/$defs/toolStat" } },
        tokens: { $ref: "#/$defs/tokenStats" },
      },
    },
    blockKind: { enum: ["thinking", "text", "tool_use", "other"] },
    modelPhase: {
      type: "object",
      required: ["kind", "position", "ms", "pctOfModel", "slices"],
      properties: {
        kind: { $ref: "#/$defs/blockKind" },
        position: { enum: ["first", "continuation"] },
        ms: { type: "number", minimum: 0 },
        pctOfModel: { type: "number", minimum: 0 },
        slices: { type: "integer", minimum: 0 },
      },
    },
    modelRequest: {
      type: "object",
      required: [
        "key",
        "requestId",
        "index",
        "turnIndex",
        "at",
        "stopReason",
        "totalMs",
        "firstBlockMs",
        "continuationMs",
        "outputTokens",
        "thinkingTokens",
        "contextTokens",
        "tokensPerSec",
        "blocks",
        "cause",
        "suspect",
        "preview",
      ],
      properties: {
        key: { type: "string" },
        requestId: { type: ["string", "null"] },
        index: { type: "integer", minimum: 0 },
        turnIndex: { type: "integer", minimum: 0 },
        at: { type: ["string", "null"] },
        model: { type: ["string", "null"] },
        effort: { type: ["string", "null"] },
        stopReason: { type: ["string", "null"] },
        totalMs: { type: "number", minimum: 0 },
        firstBlockMs: { type: "number", minimum: 0 },
        continuationMs: { type: "number", minimum: 0 },
        outputTokens: { type: "number", minimum: 0 },
        thinkingTokens: { type: "number", minimum: 0 },
        contextTokens: { type: "number", minimum: 0 },
        tokensPerSec: { type: ["number", "null"] },
        blocks: { type: "array", items: { $ref: "#/$defs/blockKind" } },
        cause: {
          type: "object",
          required: ["kind", "name"],
          properties: {
            kind: { enum: ["prompt", "tool", "other"] },
            name: { type: ["string", "null"] },
          },
        },
        suspect: { oneOf: [{ enum: ["api_error", "stalled"] }, { type: "null" }] },
        preview: { type: "string" },
      },
    },
    modelRollup: {
      type: "object",
      required: ["key", "ms", "requests", "pctOfModel"],
      properties: {
        key: { type: "string" },
        ms: { type: "number", minimum: 0 },
        requests: { type: "integer", minimum: 0 },
        pctOfModel: { type: "number", minimum: 0 },
      },
    },
    modelBreakdown: {
      type: "object",
      required: [
        "totalMs",
        "phases",
        "requests",
        "suspect",
        "suspectMs",
        "stallThresholdTokensPerSec",
        "contextLatency",
        "byCause",
        "byModel",
        "byEffort",
        "coverage",
        "precision",
      ],
      properties: {
        totalMs: { type: "number", minimum: 0 },
        phases: { type: "array", items: { $ref: "#/$defs/modelPhase" } },
        requests: { type: "array", items: { $ref: "#/$defs/modelRequest" } },
        suspect: {
          type: "array",
          items: {
            type: "object",
            required: ["reason", "ms", "requests", "pctOfModel", "kinds"],
            properties: {
              reason: { enum: ["api_error", "stalled"] },
              ms: { type: "number", minimum: 0 },
              requests: { type: "integer", minimum: 0 },
              pctOfModel: { type: "number", minimum: 0 },
              kinds: { type: "array", items: { type: "string" } },
            },
          },
        },
        suspectMs: { type: "number", minimum: 0 },
        stallThresholdTokensPerSec: { type: "number", minimum: 0 },
        contextLatency: {
          oneOf: [
            {
              type: "object",
              required: ["correlation", "requests"],
              properties: {
                correlation: { type: "number", minimum: -1, maximum: 1 },
                requests: { type: "integer", minimum: 0 },
              },
            },
            { type: "null" },
          ],
        },
        byCause: { type: "array", items: { $ref: "#/$defs/modelRollup" } },
        byModel: { type: "array", items: { $ref: "#/$defs/modelRollup" } },
        byEffort: { type: "array", items: { $ref: "#/$defs/modelRollup" } },
        coverage: {
          type: "object",
          required: ["requestsWithBlockSplit", "totalRequests"],
          properties: {
            requestsWithBlockSplit: { type: "integer", minimum: 0 },
            totalRequests: { type: "integer", minimum: 0 },
          },
        },
        precision: { const: "measured" },
      },
    },
    tokenBucket: {
      type: "object",
      required: ["input", "output", "thinking", "cacheRead", "cacheCreate1h", "cacheCreate5m"],
      properties: {
        input: { type: "number", minimum: 0 },
        output: { type: "number", minimum: 0 },
        thinking: { type: "number", minimum: 0 },
        cacheRead: { type: "number", minimum: 0 },
        cacheCreate1h: { type: "number", minimum: 0 },
        cacheCreate5m: { type: "number", minimum: 0 },
      },
    },
    tokenStats: {
      type: "object",
      required: ["byModel", "totals"],
      properties: {
        byModel: { type: "object", additionalProperties: { $ref: "#/$defs/tokenBucket" } },
        totals: { $ref: "#/$defs/tokenBucket" },
      },
    },
    costStats: {
      type: "object",
      required: [
        "source",
        "totalCostUSD",
        "byModel",
        "totalApiDurationMs",
        "totalToolDurationMs",
        "totalDurationMs",
        "linesAdded",
        "linesRemoved",
      ],
      properties: {
        source: { const: "cost-state" },
        totalCostUSD: { type: "number", minimum: 0 },
        byModel: { type: "object", additionalProperties: { type: "number" } },
        totalApiDurationMs: { type: "number", minimum: 0 },
        totalToolDurationMs: { type: "number", minimum: 0 },
        totalDurationMs: { type: "number", minimum: 0 },
        linesAdded: { type: "number", minimum: 0 },
        linesRemoved: { type: "number", minimum: 0 },
      },
    },
    promptPoint: {
      type: "object",
      required: ["turnIndex", "at", "preview"],
      properties: {
        turnIndex: { type: "integer", minimum: 0 },
        at: { type: ["string", "null"] },
        preview: { type: "string" },
      },
    },
    contextSeries: {
      type: "object",
      required: ["turns"],
      properties: {
        turns: {
          type: "array",
          items: {
            type: "object",
            required: ["turnIndex", "at", "cacheReadTokens", "cacheCreateTokens", "outputTokens", "thinkingTokens"],
            properties: {
              turnIndex: { type: "integer", minimum: 0 },
              at: { type: ["string", "null"] },
              cacheReadTokens: { type: "number", minimum: 0 },
              cacheCreateTokens: { type: "number", minimum: 0 },
              outputTokens: { type: "number", minimum: 0 },
              thinkingTokens: { type: "number", minimum: 0 },
            },
          },
        },
      },
    },
  },
} as const;
