/**
 * JSON Schema for the public `Profile` artifact (D8), hand-kept in lockstep
 * with the `Profile` type in profile.ts — that type is the source of truth;
 * this is its schema projection. `profile.test.ts` asserts a real assembled
 * profile validates structurally against it, so the two cannot drift silently.
 */
export const PROFILE_JSON_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "claude-profiler Profile",
  type: "object",
  required: [
    "schemaVersion",
    "generatedAt",
    "generator",
    "session",
    "timeline",
    "tools",
    "subagents",
    "tokens",
    "cost",
    "context",
    "diagnostics",
  ],
  properties: {
    schemaVersion: { const: "0.1" },
    generatedAt: { type: "string", format: "date-time" },
    generator: {
      type: "object",
      required: ["name", "version"],
      properties: {
        name: { type: "string" },
        version: { type: "string" },
      },
    },
    session: { $ref: "#/$defs/sessionMeta" },
    timeline: { $ref: "#/$defs/timeSplit" },
    tools: { type: "array", items: { $ref: "#/$defs/toolStat" } },
    subagents: { type: "array", items: { $ref: "#/$defs/subagentStat" } },
    tokens: { $ref: "#/$defs/tokenStats" },
    cost: { oneOf: [{ $ref: "#/$defs/costStats" }, { type: "null" }] },
    context: { $ref: "#/$defs/contextSeries" },
    diagnostics: {
      type: "object",
      required: ["skippedLines", "unknownRecordTypes", "unmatchedToolUses", "versionsSeen"],
      properties: {
        skippedLines: { type: "integer", minimum: 0 },
        unknownRecordTypes: { type: "object", additionalProperties: { type: "integer", minimum: 0 } },
        unmatchedToolUses: { type: "integer", minimum: 0 },
        versionsSeen: { type: "array", items: { type: "string" } },
      },
    },
  },
  $defs: {
    sessionMeta: {
      type: "object",
      required: [
        "sessionId",
        "transcriptPath",
        "spanMs",
        "ccVersions",
        "models",
        "turnCount",
        "messageCount",
        "isSidechain",
      ],
      properties: {
        sessionId: { type: "string" },
        transcriptPath: { type: "string" },
        projectPath: { type: ["string", "null"] },
        gitBranch: { type: ["string", "null"] },
        title: { type: ["string", "null"] },
        startedAt: { type: ["string", "null"], format: "date-time" },
        endedAt: { type: ["string", "null"], format: "date-time" },
        spanMs: { type: "number", minimum: 0 },
        ccVersions: { type: "array", items: { type: "string" } },
        models: { type: "array", items: { type: "string" } },
        turnCount: { type: "integer", minimum: 0 },
        messageCount: { type: "integer", minimum: 0 },
        isSidechain: { type: "boolean" },
      },
    },
    timeSplit: {
      type: "object",
      required: [
        "modelMs",
        "toolsMs",
        "userMs",
        "unaccountedMs",
        "spanMs",
        "toolsIncludeApprovals",
        "precision",
        "userGaps",
      ],
      properties: {
        modelMs: { type: "number", minimum: 0 },
        toolsMs: { type: "number", minimum: 0 },
        userMs: { type: "number", minimum: 0 },
        unaccountedMs: { type: "number", minimum: 0 },
        spanMs: { type: "number", minimum: 0 },
        toolsIncludeApprovals: { const: true },
        precision: { enum: ["derived", "exact"] },
        userGaps: {
          type: "array",
          items: {
            type: "object",
            required: ["preview", "gapMs"],
            properties: {
              preview: { type: "string" },
              gapMs: { type: "number", minimum: 0 },
            },
          },
        },
      },
    },
    toolCall: {
      type: "object",
      required: ["id", "name", "turnIndex", "startedAt", "durationMs", "isOutlier", "inputPreview"],
      properties: {
        id: { type: "string" },
        name: { type: "string" },
        turnIndex: { type: "integer", minimum: 0 },
        startedAt: { type: ["string", "null"] },
        durationMs: { type: ["number", "null"] },
        isOutlier: { type: "boolean" },
        inputPreview: { type: "string" },
        subagentRef: { type: "string" },
      },
    },
    toolStat: {
      type: "object",
      required: [
        "name",
        "kind",
        "calls",
        "totalMs",
        "typicalMs",
        "medianMs",
        "p90Ms",
        "maxMs",
        "outlierCount",
        "unfinishedCount",
        "pctOfSession",
        "callRefs",
        "exactMs",
        "approvalMs",
      ],
      properties: {
        name: { type: "string" },
        kind: { enum: ["builtin", "mcp", "task"] },
        mcpServer: { type: ["string", "null"] },
        calls: { type: "integer", minimum: 0 },
        totalMs: { type: "number", minimum: 0 },
        typicalMs: { type: "number", minimum: 0 },
        medianMs: { type: "number", minimum: 0 },
        p90Ms: { type: "number", minimum: 0 },
        maxMs: { type: "number", minimum: 0 },
        outlierCount: { type: "integer", minimum: 0 },
        unfinishedCount: { type: "integer", minimum: 0 },
        pctOfSession: { type: "number", minimum: 0 },
        callRefs: { type: "array", items: { $ref: "#/$defs/toolCall" } },
        exactMs: { type: ["number", "null"] },
        approvalMs: { type: ["number", "null"] },
      },
    },
    subagentStat: {
      type: "object",
      required: ["agentId", "transcriptPath", "parentToolCallId", "spanMs", "timeline", "tools", "tokens"],
      properties: {
        agentId: { type: "string" },
        transcriptPath: { type: "string" },
        parentToolCallId: { type: "string" },
        spanMs: { type: "number", minimum: 0 },
        timeline: { $ref: "#/$defs/timeSplit" },
        tools: { type: "array", items: { $ref: "#/$defs/toolStat" } },
        tokens: { $ref: "#/$defs/tokenStats" },
      },
    },
    tokenBucket: {
      type: "object",
      required: ["input", "output", "thinking", "cacheRead", "cacheCreate1h", "cacheCreate5m"],
      properties: {
        input: { type: "number", minimum: 0 },
        output: { type: "number", minimum: 0 },
        thinking: { type: "number", minimum: 0 },
        cacheRead: { type: "number", minimum: 0 },
        cacheCreate1h: { type: "number", minimum: 0 },
        cacheCreate5m: { type: "number", minimum: 0 },
      },
    },
    tokenStats: {
      type: "object",
      required: ["byModel", "totals"],
      properties: {
        byModel: { type: "object", additionalProperties: { $ref: "#/$defs/tokenBucket" } },
        totals: { $ref: "#/$defs/tokenBucket" },
      },
    },
    costStats: {
      type: "object",
      required: [
        "source",
        "totalCostUSD",
        "byModel",
        "totalApiDurationMs",
        "totalToolDurationMs",
        "totalDurationMs",
        "linesAdded",
        "linesRemoved",
      ],
      properties: {
        source: { const: "cost-state" },
        totalCostUSD: { type: "number", minimum: 0 },
        byModel: { type: "object", additionalProperties: { type: "number" } },
        totalApiDurationMs: { type: "number", minimum: 0 },
        totalToolDurationMs: { type: "number", minimum: 0 },
        totalDurationMs: { type: "number", minimum: 0 },
        linesAdded: { type: "number", minimum: 0 },
        linesRemoved: { type: "number", minimum: 0 },
      },
    },
    contextSeries: {
      type: "object",
      required: ["turns"],
      properties: {
        turns: {
          type: "array",
          items: {
            type: "object",
            required: ["turnIndex", "at", "cacheReadTokens", "cacheCreateTokens", "outputTokens", "thinkingTokens"],
            properties: {
              turnIndex: { type: "integer", minimum: 0 },
              at: { type: ["string", "null"] },
              cacheReadTokens: { type: "number", minimum: 0 },
              cacheCreateTokens: { type: "number", minimum: 0 },
              outputTokens: { type: "number", minimum: 0 },
              thinkingTokens: { type: "number", minimum: 0 },
            },
          },
        },
      },
    },
  },
} as const;
