#!/bin/bash
# Prints the Homebrew formula for a release of the standalone build, for the
# tap at github.com/Softjey/homebrew-tap:
#
#   scripts/homebrew-formula.sh 0.2.0 checksums.txt > Formula/claude-profiler.rb
#
# `checksums.txt` is the release's: "<sha256>  claude-profiler-<os>-<arch>.tar.gz"
# per line, as `shasum -a 256` writes it.
set -euo pipefail

version="${1:?usage: $0 <version> <checksums.txt>}"
checksums="${2:?usage: $0 <version> <checksums.txt>}"
base="https://github.com/Softjey/claude-profiler/releases/download/v$version"

sha() {
  local sum
  sum="$(awk -v f="claude-profiler-$1.tar.gz" '$2 == f || $2 == "*" f { print $1 }' "$checksums")"
  if [[ -z "$sum" ]]; then
    echo "error: claude-profiler-$1.tar.gz is not in $checksums" >&2
    exit 1
  fi
  echo "$sum"
}

# Looked up before the heredoc: a failure inside its $(...) would not stop the
# script, and a formula with an empty sha256 would go out.
darwin_arm64="$(sha darwin-arm64)"
darwin_x64="$(sha darwin-x64)"
linux_arm64="$(sha linux-arm64)"
linux_x64="$(sha linux-x64)"

cat <<EOF
# Generated by scripts/homebrew-formula.sh in Softjey/claude-profiler on each release.
class ClaudeProfiler < Formula
  desc "See where the time went in a Claude Code session"
  homepage "https://github.com/Softjey/claude-profiler"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/claude-profiler-darwin-arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$base/claude-profiler-darwin-x64.tar.gz"
      sha256 "$darwin_x64"
    end
  end

  on_linux do
    on_arm do
      url "$base/claude-profiler-linux-arm64.tar.gz"
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$base/claude-profiler-linux-x64.tar.gz"
      sha256 "$linux_x64"
    end
  end

  def install
    bin.install "claude-profiler"
    bin.install_symlink "claude-profiler" => "cprof"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/claude-profiler --version").strip
  end
end
EOF
